# Generated by Django 6.1 on 2026-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='codigo_registro',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
