# Generated by Django 6.1 on 2026-09-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_endereco_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
