# Generated by Django 6.1 on 2026-09-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_alter_endereco_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
