# Generated by Django 6.1 on 2026-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
    ]
