# Generated by Django 6.1 on 2026-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_alter_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=10, null=True),
        ),
    ]
